#!/bin/zsh
# shellcheck shell=bash
# This is only needed if building the packages separately

cert="Developer ID Installer: COMPANY_NAME_HERE"
identifier='com.github.smithjw.speedy-prestage.assets'

if [ -z "$1" ]; then
    echo "Please include the package version number when running this script"
    echo "eg ./build 1.0"
else
    pkgbuild --sign "$cert" --root pkgroot --identifier "$identifier" --version "$1" ../Built/Assets-"$1".pkg
fi

exit 0